### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [khanhtrung/TipCalculator#1]
Thanks for your submission. Can you please update your README and check on which options you have done?
We'll review and get back to you soon.

**Comment by khanhtrung** [comment]
Sorry for not replying sooner. I have updated the README and check on options that I have finished. Please review it again. Thank you.
Best regard,Tran Khanh Trung. 

```
On Saturday, October 1, 2016 11:46 AM, coderschoolreview <notifications@github.com> wrote:
```

 Thanks for your submission. Can you please update your README and check on which options you have done?
We'll review and get back to you soon.—

**Comment by khanhtrung** [comment]
Sorry for not replying sooner. I have updated the README and check on options that I have finished. 
Please review it again. Thank you.
